import ClientOnly from "./components/ClientOnly";
import "./globals.css";

import Navbar from "./components/Navbar/Navbar";

import { Nunito } from "next/font/google";
import ToasterProvider from "./providers/ToasterProvider";

import RegisterModel from "./components/models/RegisterModel";
import LoginModel from "./components/models/LoginModel";

import getCurrentUser from "./actions/getCurrentUser";
import RentModel from "./components/models/RentModel";

export const metadata = {
  title: "Airbn",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        {/* <ClientOnly> */}
          <ToasterProvider />
          <RegisterModel />
          <LoginModel />
          <RentModel />
          <Navbar currentUser={currentUser} />
        {/* </ClientOnly> */}
        <div className="pb-20 pt-28">{children}</div>
      </body>
    </html>
  );
}
